### ISSUE TITLE
用OnekeyUIApp.exe汉化后的问题

### ISSUE THREAD

**Issue by indescribableQB** [swordwjx/GitHubDeskTop3Chs#10]
用OnekeyUIApp.exe汉化后，首页变成这样了。我是用的githubdesk版本是3.4.2
![QQ截图20240723192230](https://github.com/user-attachments/assets/abde5f2d-95d9-4941-8886-7bff4c4c9092)

**Comment by swordwjx** [comment]
3.42只更新了main.js，没有对renderer.js进行汉化，OnekeyUIApp目录中是以前老版本的renderer.js，不要使用，删除。GithubDesk建议重新安装下，然后只更新main.js文件。

发件人: indescribableQB ***@***.***>
发送时间: 2024年7月23日 19:25
收件人: swordwjx/GitHubDeskTop3Chs ***@***.***>
抄送: Subscribed ***@***.***>
主题: [swordwjx/GitHubDeskTop3Chs] 用OnekeyUIApp.exe汉化后的问题 (Issue #10)


用OnekeyUIApp.exe汉化后，首页变成这样了。我是用的githubdesk版本是3.4.2
QQ.20240723192230.png (view on web)<https://github.com/user-attachments/assets/abde5f2d-95d9-4941-8886-7bff4c4c9092>
