### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by buiawpkgew1** [swordwjx/GitHubDeskTop3Chs#6]
![image](https://user-images.githubusercontent.com/71136405/180918140-083a3bf3-970e-4393-bc4d-10e52f148a9f.png)
全部一样

**Comment by swordwjx** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    没看明白，没有做权限限制，你也可以访问Gtiee下载。
        
            https://gitee.com/lswjx/github-desktop-3-CHS
        
    
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        7/26/2022 11:41
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              [swordwjx/GitHubDeskTop3Chs] bug (Issue #6)
        
      
    
  
  



全部一样
